# Generated by Django 5.2.1 on 2025-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vip_status',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
    ]
