# Generated by Django 5.2.1 on 2025-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='press',
            field=models.CharField(max_length=100, null=True, verbose_name='Press'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
    ]
