# Generated by Django 5.2.1 on 2025-05-27 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_customer_vip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='final_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Final Total Amount (Paid)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vip_discount_applied',
            field=models.BooleanField(default=False, verbose_name='VIP Discount Applied'),
        ),
    ]
