# Generated by Django 5.2.1 on 2025-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_order_total_amount_order_final_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Total Amount'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Original Unit Price (下单时原单价)'),
        ),
    ]
